# Casino Management Data Analysis

In [4]:
# Create the Dataset
import pandas as pd
import random

random.seed(42)
games = ["Poker", "Blackjack", "Roulette", "Slots", "Baccarat"]
cities = ["Mumbai", "Delhi", "Kolkata", "Bangalore", "Chennai"]
genders = ["Male", "Female"]
data = []
for i in range(1, 301):
    age = random.randint(18, 65)
    bet = random.randint(500, 10000)
    win = random.randint(0, 15000)
    data.append([
        i,
        f"Player_{i}",
        age,
        random.choice(genders),
        random.choice(games),
        bet,
        win,
        random.choice(cities),
        random.choice(["Yes", "No"])])
df = pd.DataFrame(data, columns=[
    "PlayerID",
    "Name",
    "Age",
    "Gender",
    "Game",
    "BetAmount",
    "WinAmount",
    "City",
    "VIP"])
df.to_csv("casino_data.csv", index=False)
print("Dataset Created Successfully!")

Dataset Created Successfully!

### Exploring the Data

In [6]:
df = pd.read_csv("casino_data.csv")

In [8]:
df.head()

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes
2,3,Player_3,19,Male,Baccarat,2035,3582,Chennai,Yes
3,4,Player_4,53,Female,Blackjack,3757,11731,Bangalore,No
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes

In [10]:
df.tail()

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
295,296,Player_296,21,Male,Roulette,9843,9204,Chennai,No
296,297,Player_297,22,Female,Baccarat,6829,8261,Kolkata,Yes
297,298,Player_298,26,Female,Roulette,2084,6453,Chennai,No
298,299,Player_299,27,Female,Baccarat,3761,9870,Mumbai,Yes
299,300,Player_300,20,Female,Slots,2745,11691,Chennai,No

In [12]:
df.shape

(300, 9)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PlayerID   300 non-null    int64
 1   Name       300 non-null    object
 2   Age        300 non-null    int64
 3   Gender     300 non-null    object
 4   Game       300 non-null    object
 5   BetAmount  300 non-null    int64
 6   WinAmount  300 non-null    int64
 7   City       300 non-null    object
 8   VIP        300 non-null    object
dtypes: int64(4), object(5)
memory usage: 21.2+ KB

In [16]:
df.describe()

         PlayerID         Age    BetAmount     WinAmount
count  300.000000  300.000000   300.000000    300.000000
mean   150.500000   41.443333  5306.816667   7441.446667
std     86.746758   13.614869  2757.281459   4394.667803
min      1.000000   18.000000   535.000000    126.000000
25%     75.750000   29.000000  2930.500000   3618.750000
50%    150.500000   41.000000  5372.500000   7693.000000
75%    225.250000   53.250000  7605.750000  11346.000000
max    300.000000   65.000000  9919.000000  14967.000000

In [18]:
df.columns

Index(['PlayerID', 'Name', 'Age', 'Gender', 'Game', 'BetAmount', 'WinAmount',
       'City', 'VIP'],
      dtype='object')

In [20]:
df.isnull().sum()

PlayerID     0
Name         0
Age          0
Gender       0
Game         0
BetAmount    0
WinAmount    0
City         0
VIP          0
dtype: int64

In [22]:
df.duplicated().sum()

0

### Filtering the data

In [26]:
# Show Players older than 40
df[df["Age"] > 40]

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes
3,4,Player_4,53,Female,Blackjack,3757,11731,Bangalore,No
7,8,Player_8,42,Female,Baccarat,1791,9044,Kolkata,Yes
8,9,Player_9,63,Male,Roulette,1639,750,Mumbai,Yes
...,...,...,...,...,...,...,...,...,...
286,287,Player_287,63,Female,Slots,5731,12029,Delhi,No
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes
289,290,Player_290,42,Male,Roulette,7350,4067,Chennai,No
293,294,Player_294,52,Male,Slots,633,13880,Delhi,No
294,295,Player_295,64,Female,Roulette,6492,12515,Mumbai,No

In [30]:
# Show VIP players
df[df["VIP"] == "Yes"]

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes
2,3,Player_3,19,Male,Baccarat,2035,3582,Chennai,Yes
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes
6,7,Player_7,40,Male,Slots,4833,13223,Chennai,Yes
...,...,...,...,...,...,...,...,...,...
277,278,Player_278,26,Male,Poker,7588,8238,Chennai,Yes
279,280,Player_280,23,Female,Blackjack,4605,3216,Kolkata,Yes
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes
296,297,Player_297,22,Female,Baccarat,6829,8261,Kolkata,Yes
298,299,Player_299,27,Female,Baccarat,3761,9870,Mumbai,Yes

In [32]:
# Show Bet > 7000
df[df["BetAmount"] > 7000]

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
14,15,Player_15,59,Female,Blackjack,8679,6482,Kolkata,Yes
15,16,Player_16,33,Female,Baccarat,9697,8830,Bangalore,No
18,19,Player_19,42,Female,Baccarat,8168,8669,Mumbai,Yes
19,20,Player_20,61,Female,Roulette,9297,12302,Mumbai,No
26,27,Player_27,51,Male,Roulette,7432,3470,Bangalore,No
...,...,...,...,...,...,...,...,...,...
285,286,Player_286,48,Female,Baccarat,8109,3342,Delhi,No
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes
288,289,Player_289,35,Male,Poker,7866,4061,Mumbai,No
289,290,Player_290,42,Male,Roulette,7350,4067,Chennai,No
295,296,Player_296,21,Male,Roulette,9843,9204,Chennai,No

In [34]:
# Show female VIP players
df[(df["Gender"]=="Female") & (df["VIP"]=="Yes")]

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes
7,8,Player_8,42,Female,Baccarat,1791,9044,Kolkata,Yes
10,11,Player_11,40,Female,Poker,3932,10980,Chennai,Yes
11,12,Player_12,52,Female,Slots,4510,2677,Kolkata,Yes
...,...,...,...,...,...,...,...,...,...
273,274,Player_274,49,Female,Slots,930,5912,Chennai,Yes
279,280,Player_280,23,Female,Blackjack,4605,3216,Kolkata,Yes
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes
296,297,Player_297,22,Female,Baccarat,6829,8261,Kolkata,Yes
298,299,Player_299,27,Female,Baccarat,3761,9870,Mumbai,Yes

In [36]:
# Blackjack players
df[df["Game"]=="Blackjack"]

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
3,4,Player_4,53,Female,Blackjack,3757,11731,Bangalore,No
12,13,Player_13,61,Male,Blackjack,5813,13809,Mumbai,No
14,15,Player_15,59,Female,Blackjack,8679,6482,Kolkata,Yes
27,28,Player_28,46,Male,Blackjack,8979,7397,Delhi,Yes
30,31,Player_31,50,Female,Blackjack,4399,4562,Chennai,Yes
31,32,Player_32,64,Female,Blackjack,9855,9440,Bangalore,No
35,36,Player_36,45,Female,Blackjack,3506,4563,Mumbai,No
39,40,Player_40,62,Female,Blackjack,9605,10844,Delhi,No
42,43,Player_43,29,Male,Blackjack,1622,9749,Bangalore,Yes
49,50,Player_50,60,Male,Blackjack,9586,4905,Kolkata,Yes
53,54,Player_54,39,Female,Blackjack,2643,10438,Bangalore,No
54,55,Player_55,53,Male,Blackjack,658,1832,Chennai,Yes
55,56,Player_56,41,Female,Blackjack,9552,2426,Mumbai,No
56,57,Player_57,41,Female,Blackjack,1153,14727,Delhi,Yes
68,69,Player_69,62,Male,Blackjack,5344,9083,Bangalore,No
78,79,Player_79,46,Female,Blackjack,8770,6991,Bangalore,No
80,81,Player_81,35,Female,Blackjack,7706,1269,Kolkata,No
81,82,Player_82,38,Male,Blackjack,9349,1320,Delhi,No
92,93,Player_93,59,Male,Blackjack,1159,12357,Delhi,Yes
94,95,Player_95,47,Female,Blackjack,4698,12564,Chennai,Yes
112,113,Player_113,35,Female,Blackjack,1245,893,Bangalore,Yes
115,116,Player_116,49,Male,Blackjack,1713,9453,Delhi,No
119,120,Player_120,58,Male,Blackjack,3957,4335,Delhi,Yes
123,124,Player_124,59,Female,Blackjack,2941,14883,Mumbai,Yes
135,136,Player_136,25,Male,Blackjack,972,10322,Kolkata,Yes
142,143,Player_143,47,Male,Blackjack,5772,14247,Chennai,No
144,145,Player_145,60,Male,Blackjack,2992,8115,Chennai,No
152,153,Player_153,51,Male,Blackjack,7251,9272,Delhi,Yes
163,164,Player_164,65,Male,Blackjack,7307,2877,Chennai,No
164,165,Player_165,51,Female,Blackjack,8721,14966,Kolkata,No
179,180,Player_180,27,Female,Blackjack,2629,8850,Mumbai,Yes
194,195,Player_195,40,Male,Blackjack,2197,9468,Bangalore,Yes
205,206,Player_206,18,Male,Blackjack,3849,4938,Kolkata,No
215,216,Player_216,24,Male,Blackjack,2899,4193,Chennai,Yes
230,231,Player_231,29,Female,Blackjack,4009,5598,Delhi,Yes
241,242,Player_242,33,Female,Blackjack,6826,1337,Mumbai,No
242,243,Player_243,24,Male,Blackjack,5993,12965,Mumbai,No
244,245,Player_245,23,Male,Blackjack,811,4193,Chennai,No
247,248,Player_248,58,Male,Blackjack,8943,9421,Kolkata,No
248,249,Player_249,18,Female,Blackjack,6280,3941,Mumbai,No
252,253,Player_253,20,Female,Blackjack,6272,8945,Bangalore,No
269,270,Player_270,31,Female,Blackjack,5178,11370,Mumbai,Yes
272,273,Player_273,41,Male,Blackjack,8835,3673,Delhi,Yes
278,279,Player_279,37,Female,Blackjack,3197,2653,Kolkata,No
279,280,Player_280,23,Female,Blackjack,4605,3216,Kolkata,Yes
280,281,Player_281,50,Male,Blackjack,3262,9696,Chennai,No
284,285,Player_285,37,Male,Blackjack,7930,1195,Bangalore,No
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes
291,292,Player_292,19,Female,Blackjack,1975,6442,Delhi,No

### Sorting

In [39]:
# Sort by Highest Bet
df.sort_values(by="BetAmount", ascending=False)

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
275,276,Player_276,44,Male,Roulette,9919,1208,Mumbai,No
113,114,Player_114,18,Female,Slots,9905,4658,Bangalore,No
31,32,Player_32,64,Female,Blackjack,9855,9440,Bangalore,No
295,296,Player_296,21,Male,Roulette,9843,9204,Chennai,No
102,103,Player_103,47,Female,Roulette,9836,9999,Mumbai,No
...,...,...,...,...,...,...,...,...,...
54,55,Player_55,53,Male,Blackjack,658,1832,Chennai,Yes
46,47,Player_47,22,Male,Poker,652,7508,Chennai,Yes
293,294,Player_294,52,Male,Slots,633,13880,Delhi,No
159,160,Player_160,35,Male,Baccarat,632,9272,Bangalore,No
38,39,Player_39,42,Female,Slots,535,6396,Kolkata,No

In [41]:
# Sort by Highest Win Amount
df.sort_values(by="WinAmount", ascending=False)

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
268,269,Player_269,51,Male,Roulette,6840,14967,Kolkata,No
164,165,Player_165,51,Female,Blackjack,8721,14966,Kolkata,No
123,124,Player_124,59,Female,Blackjack,2941,14883,Mumbai,Yes
239,240,Player_240,35,Male,Slots,7861,14832,Mumbai,Yes
235,236,Player_236,37,Male,Roulette,8184,14810,Chennai,No
...,...,...,...,...,...,...,...,...,...
143,144,Player_144,32,Female,Slots,7230,715,Bangalore,No
240,241,Player_241,46,Female,Poker,6227,436,Bangalore,No
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes
91,92,Player_92,23,Male,Roulette,8205,317,Delhi,Yes
206,207,Player_207,38,Female,Slots,2465,126,Delhi,Yes

In [43]:
# Sort Youngest to Oldest
df.sort_values(by="Age")

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
248,249,Player_249,18,Female,Blackjack,6280,3941,Mumbai,No
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes
113,114,Player_114,18,Female,Slots,9905,4658,Bangalore,No
98,99,Player_99,18,Female,Poker,7382,13473,Bangalore,No
205,206,Player_206,18,Male,Blackjack,3849,4938,Kolkata,No
...,...,...,...,...,...,...,...,...,...
294,295,Player_295,64,Female,Roulette,6492,12515,Mumbai,No
109,110,Player_110,64,Male,Baccarat,3655,5169,Delhi,Yes
163,164,Player_164,65,Male,Blackjack,7307,2877,Chennai,No
182,183,Player_183,65,Female,Roulette,1541,7802,Chennai,Yes
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes

In [45]:
# Sort Oldest to Youngest
df.sort_values(by="Age", ascending=False)

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes
182,183,Player_183,65,Female,Roulette,1541,7802,Chennai,Yes
163,164,Player_164,65,Male,Blackjack,7307,2877,Chennai,No
109,110,Player_110,64,Male,Baccarat,3655,5169,Delhi,Yes
294,295,Player_295,64,Female,Roulette,6492,12515,Mumbai,No
...,...,...,...,...,...,...,...,...,...
113,114,Player_114,18,Female,Slots,9905,4658,Bangalore,No
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes
98,99,Player_99,18,Female,Poker,7382,13473,Bangalore,No
205,206,Player_206,18,Male,Blackjack,3849,4938,Kolkata,No
248,249,Player_249,18,Female,Blackjack,6280,3941,Mumbai,No

In [47]:
# Sort by Game, then Bet Amount
df.sort_values(by=["Game", "BetAmount"])

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
159,160,Player_160,35,Male,Baccarat,632,9272,Bangalore,No
180,181,Player_181,26,Male,Baccarat,743,5869,Kolkata,Yes
28,29,Player_29,39,Male,Baccarat,844,9638,Delhi,Yes
292,293,Player_293,21,Female,Baccarat,1328,4609,Bangalore,No
133,134,Player_134,44,Female,Baccarat,1388,3073,Bangalore,No
...,...,...,...,...,...,...,...,...,...
100,101,Player_101,57,Female,Slots,9317,12691,Bangalore,No
172,173,Player_173,60,Male,Slots,9350,6866,Mumbai,No
283,284,Player_284,58,Female,Slots,9438,4745,Delhi,No
221,222,Player_222,47,Male,Slots,9581,12973,Chennai,Yes
113,114,Player_114,18,Female,Slots,9905,4658,Bangalore,No

In [49]:
# Sort by Game, then Highest Bet
df.sort_values(by=["Game", "BetAmount"], ascending=[True, False])

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP
118,119,Player_119,37,Male,Baccarat,9816,10174,Mumbai,Yes
177,178,Player_178,26,Male,Baccarat,9750,3362,Delhi,Yes
15,16,Player_16,33,Female,Baccarat,9697,8830,Bangalore,No
196,197,Player_197,45,Male,Baccarat,9690,12573,Kolkata,Yes
57,58,Player_58,40,Female,Baccarat,9673,14485,Delhi,Yes
...,...,...,...,...,...,...,...,...,...
273,274,Player_274,49,Female,Slots,930,5912,Chennai,Yes
61,62,Player_62,32,Male,Slots,887,10813,Kolkata,No
84,85,Player_85,42,Female,Slots,820,14036,Mumbai,No
293,294,Player_294,52,Male,Slots,633,13880,Delhi,No
38,39,Player_39,42,Female,Slots,535,6396,Kolkata,No

### Groupby

In [58]:
# Average amount players bet in each game.
df.groupby("Game")["BetAmount"].mean()

Game
Baccarat     5271.666667
Blackjack    5148.400000
Poker        5220.200000
Roulette     5618.376812
Slots        5207.187500
Name: BetAmount, dtype: float64

In [60]:
# Average Win Amount by Game
df.groupby("Game")["WinAmount"].mean()

Game
Baccarat     7838.807018
Blackjack    7201.880000
Poker        7428.516667
Roulette     7102.347826
Slots        7652.421875
Name: WinAmount, dtype: float64

In [68]:
# Total Bet Amount by Game
df.groupby("Game")["BetAmount"].sum()

Game
Baccarat     300485
Blackjack    257420
Poker        313212
Roulette     387668
Slots        333260
Name: BetAmount, dtype: int64

In [70]:
# Total Win Amount by Game
df.groupby("Game")["WinAmount"].sum()

Game
Baccarat     446812
Blackjack    360094
Poker        445711
Roulette     490062
Slots        489755
Name: WinAmount, dtype: int64

In [76]:
# Number of Players in Each Game
df["Game"].value_counts()

Game
Roulette     69
Slots        64
Poker        60
Baccarat     57
Blackjack    50
Name: count, dtype: int64

In [78]:
# Average Age by Game
df.groupby("Game")["Age"].mean()

Game
Baccarat     39.649123
Blackjack    43.000000
Poker        39.983333
Roulette     40.985507
Slots        43.687500
Name: Age, dtype: float64

In [80]:
# Average Bet by Gender
df.groupby("Gender")["BetAmount"].mean()

Gender
Female    5385.645161
Male      5222.551724
Name: BetAmount, dtype: float64

In [82]:
# Average Bet by City
df.groupby("City")["BetAmount"].mean()

City
Bangalore    5325.015873
Chennai      5082.135593
Delhi        5415.035088
Kolkata      5145.936508
Mumbai       5584.000000
Name: BetAmount, dtype: float64

In [84]:
# Multiple Statistics Together
df.groupby("Game")["BetAmount"].agg(["mean", "max", "min", "sum"])

                  mean   max   min     sum
Game
Baccarat   5271.666667  9816   632  300485
Blackjack  5148.400000  9855   658  257420
Poker      5220.200000  9746   652  313212
Roulette   5618.376812  9919  1034  387668
Slots      5207.187500  9905   535  333260

In [86]:
# Group by Game and calculate all four statistics for both BetAmount and WinAmount
df.groupby("Game")[["BetAmount", "WinAmount"]].agg(["mean", "sum", "max", "min"])

             BetAmount                        WinAmount
                  mean     sum   max   min         mean     sum    max   min
Game
Baccarat   5271.666667  300485  9816   632  7838.807018  446812  14485  1084
Blackjack  5148.400000  257420  9855   658  7201.880000  360094  14966   409
Poker      5220.200000  313212  9746   652  7428.516667  445711  14441   436
Roulette   5618.376812  387668  9919  1034  7102.347826  490062  14967   317
Slots      5207.187500  333260  9905   535  7652.421875  489755  14832   126

### Pivot Table

In [88]:
# Shows the average bet for each game
df.pivot_table(values="BetAmount", index="Game", aggfunc="mean")

             BetAmount
Game
Baccarat   5271.666667
Blackjack  5148.400000
Poker      5220.200000
Roulette   5618.376812
Slots      5207.187500

In [90]:
# Shows the average winnings for each game
df.pivot_table(values="WinAmount", index="Game", aggfunc="mean")

             WinAmount
Game
Baccarat   7838.807018
Blackjack  7201.880000
Poker      7428.516667
Roulette   7102.347826
Slots      7652.421875

In [93]:
# Average Bet by Game and Gender
df.pivot_table(values="BetAmount", index="Game", columns="Gender", aggfunc="mean")

Gender          Female         Male
Game
Baccarat   5192.656250  5372.800000
Blackjack  5393.346154  4883.041667
Poker      5538.333333  4902.066667
Roulette   5843.567568  5358.000000
Slots      4867.366667  5507.029412

In [95]:
# Total Bet Amount by City
df.pivot_table(values="BetAmount", index="City", aggfunc="sum")

           BetAmount
City
Bangalore     335476
Chennai       299846
Delhi         308657
Kolkata       324194
Mumbai        323872

In [97]:
#Count Players by Game
df.pivot_table(values="PlayerID", index="Game", aggfunc="count")

           PlayerID
Game
Baccarat         57
Blackjack        50
Poker            60
Roulette         69
Slots            64

In [101]:
# Multiple Statistics Together
df.pivot_table(
    values="BetAmount",
    index="Game",
    aggfunc=["mean", "max", "min", "sum"])

                  mean       max       min       sum
             BetAmount BetAmount BetAmount BetAmount
Game
Baccarat   5271.666667      9816       632    300485
Blackjack  5148.400000      9855       658    257420
Poker      5220.200000      9746       652    313212
Roulette   5618.376812      9919      1034    387668
Slots      5207.187500      9905       535    333260

In [105]:
# Feature Engineering
# Profit
df["Profit"] = df["WinAmount"] - df["BetAmount"]

In [107]:
# ROI
df["ROI"] = df["WinAmount"] / df["BetAmount"]

In [109]:
# Age Group
df["AgeGroup"] = df["Age"].apply(
    lambda x: "Young" if x < 30
    else "Adult" if x < 50
    else "Senior")

In [111]:
# Big Bettor
df["BigBettor"] = df["BetAmount"] > 5000

In [113]:
# High Winner
df["HighWinner"] = df["WinAmount"] > 10000

In [115]:
df.head()

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP,Profit,ROI,AgeGroup,BigBettor,HighWinner
0,1,Player_1,58,Female,Blackjack,2324,409,Delhi,Yes,-1915,0.175990,Senior,False,False
1,2,Player_2,65,Male,Baccarat,2179,11087,Bangalore,Yes,8908,5.088114,Senior,False,True
2,3,Player_3,19,Male,Baccarat,2035,3582,Chennai,Yes,1547,1.760197,Young,False,False
3,4,Player_4,53,Female,Blackjack,3757,11731,Bangalore,No,7974,3.122438,Senior,False,True
4,5,Player_5,18,Female,Roulette,3115,11438,Kolkata,Yes,8323,3.671910,Young,False,True

In [120]:
# Which game has the highest average profit?
df.groupby("Game")["Profit"].mean().sort_values(ascending=False)

Game
Baccarat     2567.140351
Slots        2445.234375
Poker        2208.316667
Blackjack    2053.480000
Roulette     1483.971014
Name: Profit, dtype: float64

In [122]:
# Which city has the highest total betting amount
df.groupby("City")["BetAmount"].sum().sort_values(ascending=False)

City
Bangalore    335476
Kolkata      324194
Mumbai       323872
Delhi        308657
Chennai      299846
Name: BetAmount, dtype: int64

In [124]:
# Which game has the highest average ROI?
df.groupby("Game")["ROI"].mean().sort_values(ascending=False)

Game
Slots        2.597612
Baccarat     2.429435
Blackjack    2.376266
Poker        2.143354
Roulette     1.827495
Name: ROI, dtype: float64

In [126]:
# Who are the 10 biggest winners?
df.sort_values("WinAmount", ascending=False).head(10)

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP,Profit,ROI,AgeGroup,BigBettor,HighWinner
268,269,Player_269,51,Male,Roulette,6840,14967,Kolkata,No,8127,2.188158,Senior,True,True
164,165,Player_165,51,Female,Blackjack,8721,14966,Kolkata,No,6245,1.716088,Senior,True,True
123,124,Player_124,59,Female,Blackjack,2941,14883,Mumbai,Yes,11942,5.060524,Senior,False,True
239,240,Player_240,35,Male,Slots,7861,14832,Mumbai,Yes,6971,1.886783,Adult,True,True
235,236,Player_236,37,Male,Roulette,8184,14810,Chennai,No,6626,1.809629,Adult,True,True
161,162,Player_162,58,Male,Roulette,2091,14801,Bangalore,Yes,12710,7.078431,Senior,False,True
56,57,Player_57,41,Female,Blackjack,1153,14727,Delhi,Yes,13574,12.772767,Adult,False,True
257,258,Player_258,41,Female,Slots,7659,14573,Bangalore,No,6914,1.902729,Adult,True,True
188,189,Player_189,45,Male,Slots,7898,14550,Kolkata,No,6652,1.842239,Adult,True,True
171,172,Player_172,24,Male,Slots,4346,14536,Bangalore,No,10190,3.344685,Young,False,True

In [130]:
# Who are the 10 biggest losers?
df.sort_values("Profit").head(10)

,PlayerID,Name,Age,Gender,Game,BetAmount,WinAmount,City,VIP,Profit,ROI,AgeGroup,BigBettor,HighWinner
275,276,Player_276,44,Male,Roulette,9919,1208,Mumbai,No,-8711,0.121786,Adult,True,False
81,82,Player_82,38,Male,Blackjack,9349,1320,Delhi,No,-8029,0.141192,Adult,True,False
287,288,Player_288,50,Female,Blackjack,9702,1739,Bangalore,Yes,-7963,0.179241,Senior,True,False
238,239,Player_239,41,Male,Roulette,9585,1680,Mumbai,Yes,-7905,0.175274,Adult,True,False
91,92,Player_92,23,Male,Roulette,8205,317,Delhi,Yes,-7888,0.038635,Young,True,False
219,220,Player_220,40,Female,Slots,8812,1215,Bangalore,Yes,-7597,0.137880,Adult,True,False
167,168,Player_168,34,Female,Roulette,9291,2024,Kolkata,No,-7267,0.217845,Adult,True,False
55,56,Player_56,41,Female,Blackjack,9552,2426,Mumbai,No,-7126,0.253978,Adult,True,False
129,130,Player_130,58,Female,Roulette,8556,1494,Bangalore,No,-7062,0.174614,Senior,True,False
50,51,Player_51,24,Female,Roulette,9564,2546,Chennai,Yes,-7018,0.266207,Young,True,False

### Final Business Questions
1. The game with the highest average profit was ________.

2. The city with the highest total betting amount was ________.

3. The game with the highest average ROI was ________.

4. The highest-winning players were identified by comparing WinAmount.

5. The biggest losses were identified by comparing Profit.

In [141]:
# 1. The game with the highest average profit was _______.
highest_avg_profit_game = df.groupby("Game")["Profit"].mean().idxmax()
print("The game with the highest average profit was:", highest_avg_profit_game)

The game with the highest average profit was: Baccarat

In [137]:
# 2. The city with the highest total betting amount was _______.
highest_betting_city = df.groupby("City")["BetAmount"].sum().idxmax()
print("The city with the highest total betting amount was:", highest_betting_city)

The city with the highest total betting amount was: Bangalore

In [139]:
# The game with the highest average ROI was ________.
highest_roi_game = df.groupby("Game")["ROI"].mean().idxmax()
print("The game with the highest average ROI was:", highest_roi_game)

The game with the highest average ROI was: Slots

In [143]:
# 4. The highest-winning players were identified by comparing WinAmount.
top_winners = df.nlargest(10, "WinAmount")[["PlayerID", "Name", "Game", "WinAmount"]]
print(top_winners)

     PlayerID        Name       Game  WinAmount
268       269  Player_269   Roulette      14967
164       165  Player_165  Blackjack      14966
123       124  Player_124  Blackjack      14883
239       240  Player_240      Slots      14832
235       236  Player_236   Roulette      14810
161       162  Player_162   Roulette      14801
56         57   Player_57  Blackjack      14727
257       258  Player_258      Slots      14573
188       189  Player_189      Slots      14550
171       172  Player_172      Slots      14536

In [145]:
# 5. The biggest losses were identified by comparing Profit.
biggest_losses = df.nsmallest(10, "Profit")[["PlayerID", "Name", "Game", "Profit"]]
print(biggest_losses)

     PlayerID        Name       Game  Profit
275       276  Player_276   Roulette   -8711
81         82   Player_82  Blackjack   -8029
287       288  Player_288  Blackjack   -7963
238       239  Player_239   Roulette   -7905
91         92   Player_92   Roulette   -7888
219       220  Player_220      Slots   -7597
167       168  Player_168   Roulette   -7267
55         56   Player_56  Blackjack   -7126
129       130  Player_130   Roulette   -7062
50         51   Player_51   Roulette   -7018

### Casino Analytics Menu System

In [149]:
while True:
    print("\n" + "=" * 40)
    print("CASINO ANALYTICS SYSTEM")
    print("=" * 40)
    print("1. Dataset Overview")
    print("2. Game Analysis")
    print("3. City Analysis")
    print("4. Top Winners")
    print("5. Biggest Losers")
    print("6. VIP Player Analysis")
    print("7. Search Player")
    print("8. Exit")
    choice = input("Enter your choice: ")
    if choice == "1":
        print("\nDATASET OVERVIEW")
        print("Total Players:", len(df))
        print("Total Games:", df["Game"].nunique())
        print("Average Bet:", df["BetAmount"].mean())
        print("Average Win:", df["WinAmount"].mean())
    elif choice == "2":
        print("\nGAME ANALYSIS")
        print(df.groupby("Game")[["BetAmount", "WinAmount", "Profit"]].mean())
    elif choice == "3":
        print("\nCITY ANALYSIS")
        print(df.groupby("City")["BetAmount"].sum().sort_values(ascending=False))
    elif choice == "4":
        print("\nTOP 10 WINNERS")
        print(df.sort_values("WinAmount", ascending=False).head(10))
    elif choice == "5":
        print("\nBIGGEST LOSERS")
        print(df.sort_values("Profit").head(10))
    elif choice == "6":
        print("\nVIP PLAYER ANALYSIS")
        print(df[df["VIP"] == "Yes"])
    elif choice == "7":
        player_id = input("Enter PlayerID: ")
        result = df[df["PlayerID"].astype(str) == player_id]
        if len(result) > 0:
            print("\nPLAYER FOUND")
            print(result)
        else:
            print("\nPlayer not found.")
    elif choice == "8":
        print("\nThank you for using Casino Analytics System ")
        break
    else:
        print("\nInvalid choice. Please select 1-8.")

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  1

DATASET OVERVIEW
Total Players: 300
Total Games: 5
Average Bet: 5306.816666666667
Average Win: 7441.446666666667

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  2

GAME ANALYSIS
             BetAmount    WinAmount       Profit
Game
Baccarat   5271.666667  7838.807018  2567.140351
Blackjack  5148.400000  7201.880000  2053.480000
Poker      5220.200000  7428.516667  2208.316667
Roulette   5618.376812  7102.347826  1483.971014
Slots      5207.187500  7652.421875  2445.234375

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  3

CITY ANALYSIS
City
Bangalore    335476
Kolkata      324194
Mumbai       323872
Delhi        308657
Chennai      299846
Name: BetAmount, dtype: int64

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  4

TOP 10 WINNERS
     PlayerID        Name  Age  Gender       Game  BetAmount  WinAmount  \
268       269  Player_269   51    Male   Roulette       6840      14967
164       165  Player_165   51  Female  Blackjack       8721      14966
123       124  Player_124   59  Female  Blackjack       2941      14883
239       240  Player_240   35    Male      Slots       7861      14832
235       236  Player_236   37    Male   Roulette       8184      14810
161       162  Player_162   58    Male   Roulette       2091      14801
56         57   Player_57   41  Female  Blackjack       1153      14727
257       258  Player_258   41  Female      Slots       7659      14573
188       189  Player_189   45    Male      Slots       7898      14550
171       172  Player_172   24    Male      Slots       4346      14536

          City  VIP  Profit        ROI AgeGroup  BigBettor  HighWinner
268    Kolkata   No    8127   2.188158   Senior       True        True
164    Kolkata   No    6245   1.716088   Senior       True        True
123     Mumbai  Yes   11942   5.060524   Senior      False        True
239     Mumbai  Yes    6971   1.886783    Adult       True        True
235    Chennai   No    6626   1.809629    Adult       True        True
161  Bangalore  Yes   12710   7.078431   Senior      False        True
56       Delhi  Yes   13574  12.772767    Adult      False        True
257  Bangalore   No    6914   1.902729    Adult       True        True
188    Kolkata   No    6652   1.842239    Adult       True        True
171  Bangalore   No   10190   3.344685    Young      False        True

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  5

BIGGEST LOSERS
     PlayerID        Name  Age  Gender       Game  BetAmount  WinAmount  \
275       276  Player_276   44    Male   Roulette       9919       1208
81         82   Player_82   38    Male  Blackjack       9349       1320
287       288  Player_288   50  Female  Blackjack       9702       1739
238       239  Player_239   41    Male   Roulette       9585       1680
91         92   Player_92   23    Male   Roulette       8205        317
219       220  Player_220   40  Female      Slots       8812       1215
167       168  Player_168   34  Female   Roulette       9291       2024
55         56   Player_56   41  Female  Blackjack       9552       2426
129       130  Player_130   58  Female   Roulette       8556       1494
50         51   Player_51   24  Female   Roulette       9564       2546

          City  VIP  Profit       ROI AgeGroup  BigBettor  HighWinner
275     Mumbai   No   -8711  0.121786    Adult       True       False
81       Delhi   No   -8029  0.141192    Adult       True       False
287  Bangalore  Yes   -7963  0.179241   Senior       True       False
238     Mumbai  Yes   -7905  0.175274    Adult       True       False
91       Delhi  Yes   -7888  0.038635    Young       True       False
219  Bangalore  Yes   -7597  0.137880    Adult       True       False
167    Kolkata   No   -7267  0.217845    Adult       True       False
55      Mumbai   No   -7126  0.253978    Adult       True       False
129  Bangalore   No   -7062  0.174614   Senior       True       False
50     Chennai  Yes   -7018  0.266207    Young       True       False

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  6

VIP PLAYER ANALYSIS
     PlayerID        Name  Age  Gender       Game  BetAmount  WinAmount  \
0           1    Player_1   58  Female  Blackjack       2324        409
1           2    Player_2   65    Male   Baccarat       2179      11087
2           3    Player_3   19    Male   Baccarat       2035       3582
4           5    Player_5   18  Female   Roulette       3115      11438
6           7    Player_7   40    Male      Slots       4833      13223
..        ...         ...  ...     ...        ...        ...        ...
277       278  Player_278   26    Male      Poker       7588       8238
279       280  Player_280   23  Female  Blackjack       4605       3216
287       288  Player_288   50  Female  Blackjack       9702       1739
296       297  Player_297   22  Female   Baccarat       6829       8261
298       299  Player_299   27  Female   Baccarat       3761       9870

          City  VIP  Profit       ROI AgeGroup  BigBettor  HighWinner
0        Delhi  Yes   -1915  0.175990   Senior      False       False
1    Bangalore  Yes    8908  5.088114   Senior      False        True
2      Chennai  Yes    1547  1.760197    Young      False       False
4      Kolkata  Yes    8323  3.671910    Young      False        True
6      Chennai  Yes    8390  2.735982    Adult      False        True
..         ...  ...     ...       ...      ...        ...         ...
277    Chennai  Yes     650  1.085662    Young       True       False
279    Kolkata  Yes   -1389  0.698371    Young      False       False
287  Bangalore  Yes   -7963  0.179241   Senior       True       False
296    Kolkata  Yes    1432  1.209694    Young       True       False
298     Mumbai  Yes    6109  2.624302    Young      False       False

[137 rows x 14 columns]

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  4

TOP 10 WINNERS
     PlayerID        Name  Age  Gender       Game  BetAmount  WinAmount  \
268       269  Player_269   51    Male   Roulette       6840      14967
164       165  Player_165   51  Female  Blackjack       8721      14966
123       124  Player_124   59  Female  Blackjack       2941      14883
239       240  Player_240   35    Male      Slots       7861      14832
235       236  Player_236   37    Male   Roulette       8184      14810
161       162  Player_162   58    Male   Roulette       2091      14801
56         57   Player_57   41  Female  Blackjack       1153      14727
257       258  Player_258   41  Female      Slots       7659      14573
188       189  Player_189   45    Male      Slots       7898      14550
171       172  Player_172   24    Male      Slots       4346      14536

          City  VIP  Profit        ROI AgeGroup  BigBettor  HighWinner
268    Kolkata   No    8127   2.188158   Senior       True        True
164    Kolkata   No    6245   1.716088   Senior       True        True
123     Mumbai  Yes   11942   5.060524   Senior      False        True
239     Mumbai  Yes    6971   1.886783    Adult       True        True
235    Chennai   No    6626   1.809629    Adult       True        True
161  Bangalore  Yes   12710   7.078431   Senior      False        True
56       Delhi  Yes   13574  12.772767    Adult      False        True
257  Bangalore   No    6914   1.902729    Adult       True        True
188    Kolkata   No    6652   1.842239    Adult       True        True
171  Bangalore   No   10190   3.344685    Young      False        True

========================================
CASINO ANALYTICS SYSTEM
========================================
1. Dataset Overview
2. Game Analysis
3. City Analysis
4. Top Winners
5. Biggest Losers
6. VIP Player Analysis
7. Search Player
8. Exit

Enter your choice:  8

Thank you for using Casino Analytics System